name = "mymemo"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "20724d8d-1f0d-4c65-abf2-0d0b96304e41"
database_name = "NOTES_R2_BUCKET"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "49125772c08942ff939464227a01b8bd"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "notes-r2-bucket"
preview_bucket_name = "notes-files-preview"
